### ISSUE TITLE
Provide a user installer for Windows

### ISSUE THREAD

**Issue by gilbertsoft** [ddev/ddev#1914]
**Is your feature request related to a problem? Please describe.**
Nowadays more and more development related products provide an user installer which installs the product to the user profile instead of the normal program files folder. This has some advantages in business environments where the user not always has the right to install products to the program files folder.

## To Do

- [ ] Sign uninstaller (#1898)
- [ ] Provide download and install images tarballs (#1922)
- [ ] Bundle ngrok with the Windows installer (#1925 )
- [ ] Add Windows ddev bash completion capability to installer (#1934)
- [ ] Uninstaller should stop running processes (winnfsd) before performing the uninstall (#1945)
- [ ] Evaluate: system restart after docker install (#1989)
- [ ] Update docs (#1990)
- [ ] Provide a separate Chocolatey installer (#1991)
- [ ] Optimize or remove Docker Desktop (#1992)
- [ ] Move all license pages before components selection
- [ ] Extract includes (DDEV and Docker) to https://github.com/GsNSIS/

**Comment by rfay** [comment]
Should we even continue to work on this issue?

**Comment by rfay** [comment]
Closing, we'll probably not keep maintaining the installer anyway.
