### ISSUE TITLE
Migrate hub.docker.com "drud" organization to "ddev"

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#4262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

We don't need the "drud" name anywhere, so time to migrate to it.

### Describe your solution

* Rename "drud" to "ddev" if that's possible and redirects work
* Otherwise, create new "ddev" organization. We'll need to get them to
    * Give us open-source rate
    * Allow unlimited downloads on it, as they do with drud.

## TODO

- [x] Push new ddev-gitpod-base image
- [x] Update ddev-gitpod-launcher to use new base
- [x] Move https://hub.docker.com/r/drud/arch-aur-builder to ddev (where is the source?). Remember to link to the source. (It's in https://github.com/ddev/ddev/blob/1d64b856423e141817a0b2aa6a9fc63d4accb86f/.circleci/aur-checker-Dockerfile)
- [x] Push new devcontainer feature. Or not?
- [x] Update upstream docker images, especially ddev-mysql etc.
- [x] Push all standard images
- [x] Push ddev/test-ssh-server - should be v1.22.0
- [x] `ddev delete images` should also delete drud/ images

**Comment by rfay** [comment]
Sent [request](https://mail.google.com/mail/u/0/#inbox/FMfcgzGrcPQQLxCZtvrsvlQsJVQQsNvb) to docker support.

**Comment by rfay** [comment]
Via docker support and a friendly previous owner of the "ddev" org, we now have that org, which will be great.

I have asked them to sponsor the open-source "ddev" org and also turn off the rate limiting that is default on hub.docker.com

**Comment by rfay** [comment]
I did the required OSS application for the ddev org on hub.docker.com
