### ISSUE TITLE
Optimize Mastodon profile

### ISSUE THREAD

**Issue by mattstein** [ddev/ddev#4729]
DDEV’s [Mastodon account](https://fosstodon.org/@ddev) could be improved as a consistent presence and marketing tool:

1. Separate DDEV’s organizational identity from Randy’s personal one.
2. Use the profile description and links carefully and authoritatively.
3. Clarify the purpose of the account and use it accordingly.

## TODO

- [x] use the [attached DDEV logo](https://user-images.githubusercontent.com/2488775/223843411-631c66a5-bca5-4d56-b226-f2bcd6a66b06.png) for the account avatar instead of Randy’s headshot
- [x] update the profile description to remove a redundant leading `DDEV` and link to GitHub that serves a narrower audience than the homepage, and clarify _what kind_ of tool it is; suggestion:
    ```
    Open-source tool for local PHP and Node.js development environments.
    ```
- [x] add a link to https://ddev.com via **Preferences** → **Appearance** → **Profile metadata** 
    > ✅ it should appear as verified since the homepage includes a link to the Mastodon profile with `rel="me"`
- [x] optionally establish a personal account that can follow and promote DDEV, and use the DDEV account strictly for official announcements, following active community members, and liking/boosting directly-relevant toots; let Randy (or others) add personal comments and humanity beyond DDEV’s organizational communication

**Comment by rfay** [comment]
Thanks, this is important, and this is an important time to do it.

**Comment by rfay** [comment]
I've done all these, thanks so much for the prod. Please check it out and close when approved.

**Comment by rfay** [comment]
Also, the password to the ddev account is in shared 1Password.

**Comment by mattstein** [comment]
![Screen Shot 2023-03-08 at 04 12 24 PM@2x](https://user-images.githubusercontent.com/2488775/223881898-8c4f0540-146a-426b-ad4c-acc38ae59439.png)

Looks good! Is there a reason you kept `ddev.com` at the end there? It seems redundant given the now-prominent link.

**Comment by rfay** [comment]
No reason. I was going through things in order :) Didn't know the metadata was still to come :)
