### ISSUE TITLE
Support PHP 8.4

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#6205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

PHP 8.4 should go into alpha before too long. It probably won't show up in deb.sury.org until a while after that. We'll probably want to provide some kind of support for it before it arrives in deb.sury.org, we've done this before in https://github.com/ddev/ddev-contrib and elsewhere.  Alpha1 is scheduled for June 6, 2024

### TODO

- [x] New ddev-php-base with 8.4 in it
- [x] Proper /etc/php from either ddev-webserver or ddev-php-base (choose which)

**Comment by rfay** [comment]
* https://github.com/oerdnj/deb.sury.org/issues/2176
