### ISSUE TITLE
Remove python/django support in v1.24.0

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#6714]
Our python/django experiment has not been a success. I propose that we remove this feature in upcoming v1.24.0

## TODO

- [ ] Remove tests (python/django/etc)
- [ ] Remove extra packages added to ddev-webserver, especially gunicorn and related
- [ ] Remove related docs
- [ ] Remove python and django project types

**Comment by rfay** [comment]
DDEV's success is based on the user community's direction and engagement. In the case of Python/Django... there weren't any users, and as a result the implementation didn't mature.
